[package]
name = "minicryptolab"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10"
aes = "0.8"
block-modes = "0.9"
rsa = "0.9"
rand = "0.8"
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
